CREATE TABLE Users (
	ID   INTEGER PRIMARY KEY AUTOINCREMENT,
	Name TEXT NOT NULL,
	Email TEXT NOT NULL,
	PhoneNr TEXT NOT NULL,
	Password TEXT NOT NULL,
	Salt TEXT NOT NULL,
	Admin BOOLEAN NOT NULL
);

CREATE TABLE Ticket (
	ID   INTEGER PRIMARY KEY AUTOINCREMENT,
	Type TEXT NOT NULL,
	Used BOOLEAN NOT NULL,
	DateEmmited DATE NOT NULL,
	DateExpiry DATE NOT NULL,
	DateUsed DATE NOT NULL,
	BuyerId INTEGER NOT NULL,
	FOREIGN KEY(BuyerID) REFERENCES Visitor(ID)
);

CREATE TABLE Visitor (
	ID   INTEGER PRIMARY KEY AUTOINCREMENT,
	Name TEXT NOT NULL,
	CreditCardID INTEGER NOT NULL,	
	FOREIGN KEY(CreditCardID) REFERENCES CreditCard(ID)		
);

CREATE TABLE Attraction (
	ID   INTEGER PRIMARY KEY AUTOINCREMENT,
	Name TEXT NOT NULL,
	Type TEXT NOT NULL,
	Operational BOOLEAN NOT NULL,
	DailyCapacity INTEGER NOT NULL,
	Price INTEGER NOT NULL
);

CREATE TABLE Event (
	ID   INTEGER PRIMARY KEY AUTOINCREMENT,
	Date DATE NOT NULL,
	Name TEXT NOT NULL,	
	Description TEXT NOT NULL
);

CREATE TABLE Visit (
	ID   INTEGER PRIMARY KEY AUTOINCREMENT,
	Date DATE NOT NULL,
	VisitorID INTEGER NOT NULL,
	AttractionID INTEGER NOT NULL,	
	FOREIGN KEY(VisitorID) REFERENCES Visitor(ID),
	FOREIGN KEY(AttractionID) REFERENCES Attraction(ID)			
);

CREATE TABLE CreditCard (
	ID   INTEGER PRIMARY KEY AUTOINCREMENT,
	Name TEXT NOT NULL,
	Number INTEGER NOT NULL,		
	MonthExpiry TEXT NOT NULL,		
	YearExpiry INTEGER NOT NULL,		
	CCV INTEGER NOT NULL		
);
